# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required version
version: 2

# Specify the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation with Sphinx, pointing to your conf.py
sphinx:
  configuration: source/conf.py

# Optional: Include additional formats if desired
# formats:
#    - pdf
#    - epub

# Python dependencies required for building documentation
# python:
#    install:
#    - requirements: requirements.txt
